# SPDX-FileCopyrightText: Ruben Talstra
# SPDX-License-Identifier: BUSL-1.1

[package]
name = "ferrochart-compile"
description = "Compiles an openEHR operational template into a FerroCHART form definition"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
