# SPDX-FileCopyrightText: Ruben Talstra
# SPDX-License-Identifier: BUSL-1.1

[package]
name = "ferrochart-compile"
description = "Compiles an openEHR operational template into a FerroCHART form definition"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
openehr-base.workspace = true
openehr-am.workspace = true
openehr-adl.workspace = true
openehr-its.workspace = true
openehr-rm.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
